module.exports = [
  "Tum Hi Ho - Arijit Singh",
  "Channa Mereya - Arijit Singh",
  "Kal Ho Naa Ho - Sonu Nigam",
  "Tujh Mein Rab Dikhta Hai - Roop Kumar Rathod",
  "Kabira - Arijit Singh",
  "Gerua - Arijit Singh",
  "Janam Janam - Arijit Singh",
  "Bekhayali - Sachet Tandon",
  "Tera Ban Jaunga - Akhil Sachdeva",
  "Phir Le Aya Dil - Rekha Bhardwaj",
  "Tumhe Dillagi - Rahat Fateh Ali Khan",
  "Pehla Nasha - Udit Narayan",
  "Dil Hai Chhota Sa - Udit Narayan",
  "Mere Dushman - Kumar Sanu",
  "Tu Hi Meri Shab Hai - K.K.",
  "O Re Piya - Rahat Fateh Ali Khan",
  "Titliaan - Harrdy Sandhu",
  "Filhaal - B Praak",
  "Lut Gaye - Jubin Nautiyal",
  "Dil Diyan Gallan - Atif Aslam",
  "Raabta - Arijit Singh",
  "Tum Hi Ana - Jubin Nautiyal",
  "Kesariya - Arijit Singh",
  "Mann Bharya - B Praak",
  "Tere Pyaar Mein - Arijit Singh",
  "Ghungroo - Arijit Singh",
  "Morni Banke - Guru Randhawa",
  "Koka - Jasmine Sandlas",
  "Chaand Baaliyan - Aditya A",
  "Rangisari - Kanishk Seth",
  "Lagdi Lahore Di - Guru Randhawa",
  "Masakali - Mohit Chauhan",
  "Main Dhoondne Ko - K.K.",
  "Param Sundari - Shreya Ghoshal",
  "O Saki Saki - Tulsi Kumar",
  "Dilbar - Neha Kakkar",
  "Swag Se Swagat - Vishal Dadlani",
  "Badtameez Dil - Benny Dayal",
  "London Thumakda - Labh Janjua",
  "Nagada Sang Dhol - Shreya Ghoshal",
  "Ghoomar - Shreya Ghoshal",
  "Deewani Mastani - Shreya Ghoshal",
  "Ae Dil Hai Mushkil - Arijit Singh",
  "Tera Hone Laga Hoon - Atif Aslam",
  "Ajab Si - K.K.",
  "Saans - Shreya Ghoshal",
  "Hawayein - Arijit Singh",
  "Tera Yaar Hoon Main - Arijit Singh",
  "Sunn Raha Hai - Shreya Ghoshal",
  "Pani Da Rang - Ayushmann Khurrana",
  "Heer - Harshdeep Kaur",
  "Satranga - Arijit Singh",
  "Arjan Vailly - Bhupinder Babbal",
  "Chaleya - Arijit Singh",
  "Heeriye - Jasleen Royal",
  "Zihaal E Miskin - Vishal Mishra",
  "Kahani Suno - Kaifi Khalil",
  "Husn - Anuv Jain",
  "Maan Meri Jaan - King",
  "Kho Gaye - Karan Aujla",
  "Apna Bana Le - Arijit Singh",
  "Ranjha - Jasleen Royal",
  "Shayad - Arijit Singh",
  "Phir Mohabbat - Arijit Singh",
  "Tujhe Kitna Chahne Lage - Jubin Nautiyal",
  "Hum Nashe Mein Toh Nahin - Arijit Singh",
  "Ishq Wala Love - Vishal Dadlani",
  "Darmiyan - Jubin Nautiyal",
  "Bin Tere - Shafqat Amanat Ali",
  "Tere Bin - Atif Aslam",
  "Mitwa - Shankar Mahadevan",
  "Maula Mere Maula - Roop Kumar Rathod",
  "Tum Tak - Arijit Singh",
  "Lagaa Chunari Mein Daag - Manna Dey",
  "Ajeeb Dastaan Hai Yeh - Lata Mangeshkar",
  "Lag Ja Gale - Lata Mangeshkar",
  "Yeh Dil Mera - Kishore Kumar",
  "Mere Mehboob - Kishore Kumar",
  "Roop Tera Mastana - Kishore Kumar",
  "O Mere Dil Ke Chain - Kishore Kumar",
  "Chura Liya Hai - Asha Bhosle",
  "Dum Maro Dum - Asha Bhosle",
  "Piya Tu Ab To Aja - Asha Bhosle",
  "Mausam Hai Aashiqui Ka - Kumar Sanu",
  "Tu Mile Dil Khile - Kumar Sanu",
  "Sajde - Kailash Kher",
  "Dil Ibaadat - K.K.",
  "Maaeri - K.K.",
  "Agar Tum Saath Ho - Alka Yagnik",
  "Mere Rashke Qamar - Nusrat Fateh Ali Khan",
  "Allah Tero Naam - Anuradha Paudwal",
  "Jab Tak Hai Jaan - Javed Ali",
  "Tere Liye - Roop Kumar Rathod",
  "Hoton Mein Aisi Baat - Lata Mangeshkar",
  "Mere Rang Mein - Kailash Kher",
  "Pyar Hua Chupke Se - Kavita Krishnamurthy",
  "Dil To Pagal Hai - Lata Mangeshkar",
  "Lagi Tose Lagan - Lata Mangeshkar",
  "Jaane Kyun - Vishal Dadlani",
  "Khalasi - Aditya Gadhvi",
];
